### ISSUE TITLE
Removing field leaves floating 'Add' button

### ISSUE THREAD

**Issue by gmh04** [edina/fieldtrip-cobweb-project#137] opened 2016-05-20 11:07 UTC
raised by  [sebastianclarke](https://github.com/sebastianclarke)

When you add a new field to the designer, it also puts an 'Add' button below it, for adding further fields afterwards.

When you click the 'X' to remove this field, the 'Add' button should be removed as well, but still remains, leaving duplicate 'Add' buttons

**Comment by rgamez** [comment] 2016-06-10 11:20
I can't reproduce it in the current [HEAD](https://github.com/edina/survey-designer/tree/80a457c9237639ffeafeb9c73290d4506151f4d9) it seems resolved by this commit: https://github.com/edina/survey-designer/commit/cb7cef3507b1defae20a169d3776d97368604b77#diff-7ef4d2bd1fc863cb28aba5c43c0e4e92R365

**Closed by rgamez** 2016-06-10 11:20 UTC
Labels: bug, survey designer
